name: testBuildDeployToCF

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

  build:
    runs-on: ubuntu-20.04
    needs: [test]

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2