name: deploy to cf

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: citizen-of-planet-earth/cf-cli-action@master
      with:
        cf_api: https://api.cf.datev.cloud
        cf_username: test
        cf_password: test
        cf_org: helloworld
        cf_space: github
        command: push -f manifest.yml
