name: deploy to cf

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: check out repository
        uses: actions/checkout@v2
      - name: deploy app
        uses: citizen-of-planet-earth/cf-cli-action@master
        with:
          cf_api: https://api.cf.datev.cloud
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_space: Development
          command: push -f manifest-dev.yml
